### ISSUE TITLE
when add tcp support for rtsp server?

### ISSUE THREAD

**Issue by intmainwjj** [pedroSG94/RTSP-Server#1]
it's an excellent project
when can add tcp support for rtsp server?

**Comment by pedroSG94** [comment]
I don't know. When I tried implement it I couldn't find a player working with TCP to debug.
Do you know a free player with TCP support?
I use VLC but by default it use UDP and I don't know how to force TCP

**Comment by intmainwjj** [comment]
please try this way:
Tools, Preferences, Input / Codec, Demuxers, RTP/RTSP, Use RTP over RTSP (TCP).













At 2020-02-20 23:35:35, "Pedro Sánchez" <notifications@github.com> wrote:

I don't know. When I tried implement it I couldn't find a player working with TCP to debug.
Do you know a free player with TCP support?
I use VLC but by default it use UDP and I don't know how to force TCP

**Comment by pedroSG94** [comment]
Thank you. I will try with this.

**Comment by pedroSG94** [comment]
I just finished this feature:
https://github.com/pedroSG94/RTSP-Server/commit/584c2a7d32b99e6fe6fcf203f9f50663543c330a
Let me know if you have any error. I didn't so much test but it is working with TCP and UDP at same time (tested with VLC and ffplay in Linux Ubuntu 18.04.3 LTS)

**Comment by intmainwjj** [comment]
It supports TCP now, thank you, And I will keep testing.
