### ISSUE TITLE
How to crop video while streaming....?

### ISSUE THREAD

**Issue by ankitda30** [pedroSG94/RTSP-Server#10]
Hi Pedro,
I'm using surfaceview to streaming video,
I need to crop perticullar region 
ex.Only half of the screen needs to crop while streaming....
what changes should I need to do please help.....!
I Used RtspServerCamera class....
I dont wanted to use setZoom function from Camera2ApiManager...

**Comment by pedroSG94** [comment]
You have 2 options:
- Use setZoom of camera1 or camera2 as you said.
- Use OpenGlView and replace rtmp-rtsp-stream-client-java:rtplibrary dependency in the module with your own library modification and modify this method to work as you want:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/utils/gl/PreviewSizeCalculator.java#L11

This method work like this. This code means:
```java
GLES20.glViewport(0, 0, previewWidth, previewHeight);
```
I want start draw in pixel 0,0 (cardinal point 0X, 0Y) and finish this draw in my max view width and my max view height (for example, if my openglview has 200x200px) this means that you are doing this:
```java
GLES20.glViewport(0, 0, 200, 200);
```
Remember that this line is used for stream result and preview when you set keepAspectRatio to false:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/utils/gl/PreviewSizeCalculator.java#L31
And this for preview only when you set keepAspectRatio to true:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/utils/gl/PreviewSizeCalculator.java#L13

Of course, you can start draw in negative points to crop it like this:
```java
GLES20.glViewport(-200, -200, previewWidth - 200, previewHeight - 200);
```
