### ISSUE TITLE
How to get RTSP Server URL with IPv6?

### ISSUE THREAD

**Issue by gushangzao007** [pedroSG94/RTSP-Server#100]
Appreciate your wonderful job!
I'm not sure that your library can support IPv6 URL of RTSP service? 
it is very important for me.  if it is not, I've no idea how to solve it. 
need your help! :)

**Comment by pedroSG94** [comment]
Hello,

IPv6 is not supported because I haven't a way to test it (I have IPv4).
It should be added in this method:
https://github.com/pedroSG94/RTSP-Server/blob/master/rtspserver/src/main/java/com/pedro/rtspserver/ServerCommandManager.kt#L176

**Comment by gushangzao007** [comment]
Thanks a lot!
I have IPv6 internet environment, may be I can help to test it if you will add this feature recently.
or I am also happy to  fork a version and try to add this feature, although I'll take some time to learn about RTSP

**Comment by pedroSG94** [comment]
Hello,

You only need to change this IP4 to IP6 depend of the type used dynamically in this line:
https://github.com/pedroSG94/RTSP-Server/blob/master/rtspserver/src/main/java/com/pedro/rtspserver/ServerCommandManager.kt#L176
And get the correct IP when you call to this method (this method get the IP of your server):
https://github.com/pedroSG94/RTSP-Server/blob/master/rtspserver/src/main/java/com/pedro/rtspserver/RtspServer.kt#L191

**Comment by gushangzao007** [comment]
Great！
Got it!
Let me Try ;)

**Comment by gushangzao007** [comment]
Got an error!  Buddy! Could you help to figure it out what is the root cause and any solution?

**What main code I have Changed:**
1.for RtspServer.kt file at #L208
before:
` .filter { address -> address?.contains(":") == false }`
after:
`.filter { address ->
      address?.contains(":") == true && // Check if the address is IPv6
              !address.startsWith("fe80") && // Exclude link-local addresses
              !address.startsWith("fc00") && // Exclude unique local addresses
              !address.startsWith("fd00") // Exclude unique local addresses
    }`

2. for ServerCommandManager.kt file at #L176
before:
`return "v=0\r\no=- 0 0 IN IP4 $serverIp\r\ns=Unnamed\r\ni=N/A\r\nc=IN IP4 $clientIp\r\nt=0 0\r\na=recvonly\r\n$videoBody$audioBody\r\n"`
after:
`return "v=0\r\no=- 0 0 IN IP6 $serverIp\r\ns=Unnamed\r\ni=N/A\r\nc=IN IP6 $clientIp\r\nt=0 0\r\na=recvonly\r\n$videoBody$audioBody\r\n"`

**What Error I got When I use remote VLC Player to connect this RTSP Server**
[logfile.txt](https://github.com/pedroSG94/RTSP-Server/files/13333471/logfile.txt)
core error infomation is :

> New client [240e:47d:dab2:c17a:14b8:2b38:855b:a543]
> SETUP rtsp://[240e:47d:dab2:c17a:cff8:ccc5:d2c9:ac11]:1935/ RTSP/1.0
> CSeq: 0
> Transport: RTP/AVP;unicast;client_port=9510-9511
> TSP/1.0 500 Internal Server Error
> Server: pedroSG94 Server
> Cseq: 0
> E  cSeq not found

**Debug to trace where does the error come from**
call stack like this:
1.RtspServer.startServer -> val client = ServerClient(...)
2.ServerClient.run() ->val response = commandsManager.createResponse(...)
3.CommandsManager.createResponse() - > Method.SETUP -> {if (track != null) else {createError(500, cSeq)}}
but unfortunately, val 'track' actual value is null. so, it creates Error 500.

**Comment by pedroSG94** [comment]
Hello,

Can you show me the value of request parameter here?:
https://github.com/pedroSG94/RTSP-Server/blob/master/rtspserver/src/main/java/com/pedro/rtspserver/ServerCommandManager.kt#L121

**Comment by gushangzao007** [comment]
yes, hold on, let me retest

**Comment by gushangzao007** [comment]
it looks like this
<img width="1510" alt="截屏2023-11-13 21 57 42" src="https://github.com/pedroSG94/RTSP-Server/assets/11475854/d2ab2c88-9c46-440b-8122-6ec2e8e86122">

**Comment by pedroSG94** [comment]
Please, show me all the value and if possible paste the value in the post instead of use an image

**Comment by pedroSG94** [comment]
Are you sure that it is all? That command should have video and audio tracks request by the player.
Can you check the string returned by the line?
https://github.com/pedroSG94/RTSP-Server/blob/master/rtspserver/src/main/java/com/pedro/rtspserver/ServerCommandManager.kt#L45
This command is send by the server to inform player tracks availables.

Also, I think that you should remove "[" and "]" characters from your ipv6

**Comment by gushangzao007** [comment]
let me check

**Comment by gushangzao007** [comment]
during the debug , it seems that the code didn't go to the #L45 .

**Comment by gushangzao007** [comment]
let me remove all '[]' and try

**Comment by gushangzao007** [comment]
got the same error.  "Cseq: 0,cSeq not found", What is the Cseq?
[Logfile.txt](https://github.com/pedroSG94/RTSP-Server/files/13337174/Logfile.txt)

**Comment by gushangzao007** [comment]
> Are you sure that it is all? That command should have video and audio tracks request by the player. Can you check the string returned by the line? https://github.com/pedroSG94/RTSP-Server/blob/master/rtspserver/src/main/java/com/pedro/rtspserver/ServerCommandManager.kt#L45 This command is send by the server to inform player tracks availables.

for the value of request , yes! it is all in my case.

**Comment by pedroSG94** [comment]
Cseq is the command sequence of the rtsp comamnds.
This is a required parameter so the library check it and if it is not available throw an error.
This is a normal connection using VLC as player:
```
2023-11-13 18:23:10.509 30060-30620 CommandsManager         com.pedro.sample                     I  OPTIONS rtsp://192.168.0.158:1935 RTSP/1.0
                                                                                                    CSeq: 2
                                                                                                    User-Agent: LibVLC/3.0.19 (LIVE555 Streaming Media v2016.11.28)
2023-11-13 18:23:10.512 30060-30620 Client                  com.pedro.sample                     I  RTSP/1.0 200 OK
                                                                                                    Server: pedroSG94 Server
                                                                                                    Cseq: 2
                                                                                                    Public: DESCRIBE,SETUP,TEARDOWN,PLAY,PAUSE
2023-11-13 18:23:10.517 30060-30620 CommandsManager         com.pedro.sample                     I  DESCRIBE rtsp://192.168.0.158:1935 RTSP/1.0
                                                                                                    CSeq: 3
                                                                                                    User-Agent: LibVLC/3.0.19 (LIVE555 Streaming Media v2016.11.28)
                                                                                                    Accept: application/sdp
2023-11-13 18:23:10.553 30060-30620 Client                  com.pedro.sample                     I  RTSP/1.0 200 OK
                                                                                                    Server: pedroSG94 Server
                                                                                                    Cseq: 3
                                                                                                    Content-Length: 440
                                                                                                    Content-Base: 192.168.0.158:1935/
                                                                                                    Content-Type: application/sdp
                                                                                                    
                                                                                                    v=0
                                                                                                    o=- 0 0 IN IP4 192.168.0.158
                                                                                                    s=Unnamed
                                                                                                    i=N/A
                                                                                                    c=IN IP4 192.168.0.146
                                                                                                    t=0 0
                                                                                                    a=recvonly
                                                                                                    m=video 0 RTP/AVP 96
                                                                                                    a=rtpmap:96 H264/90000
                                                                                                    a=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAHqy0DwKNNQICAgeKFVA=,aO4Niw==
                                                                                                    a=control:streamid=0
                                                                                                    m=audio 0 RTP/AVP 97
                                                                                                    a=rtpmap:97 MPEG4-GENERIC/32000/2
                                                                                                    a=fmtp:97 profile-level-id=1; mode=AAC-hbr; config=1290; sizelength=13; indexlength=3; indexdeltalength=3
                                                                                                    a=control:streamid=1
2023-11-13 18:23:10.559 30060-30620 CommandsManager         com.pedro.sample                     I  SETUP 192.168.0.158:1935/streamid=0 RTSP/1.0
                                                                                                    CSeq: 4
                                                                                                    User-Agent: LibVLC/3.0.19 (LIVE555 Streaming Media v2016.11.28)
                                                                                                    Transport: RTP/AVP;unicast;client_port=57382-57383
2023-11-13 18:23:10.562 30060-30620 ServerCommandManager    com.pedro.sample                     I  Video ports: [57382, 57383]
2023-11-13 18:23:10.563 30060-30620 ServerCommandManager    com.pedro.sample                     I  Video ports: [57382, 57383]
2023-11-13 18:23:10.563 30060-30620 Client                  com.pedro.sample                     I  RTSP/1.0 200 OK
                                                                                                    Server: pedroSG94 Server
                                                                                                    Cseq: 4
                                                                                                    Content-Length: 0
                                                                                                    Transport: RTP/AVP/UDP;unicast;destination=192.168.0.146;client_port=57382-57383;server_port=5006-5007;mode=play
                                                                                                    Session: 1185d20035702ca
                                                                                                    Cache-Control: no-cache
2023-11-13 18:23:10.572 30060-30620 CommandsManager         com.pedro.sample                     I  SETUP 192.168.0.158:1935/streamid=1 RTSP/1.0
                                                                                                    CSeq: 5
                                                                                                    User-Agent: LibVLC/3.0.19 (LIVE555 Streaming Media v2016.11.28)
                                                                                                    Transport: RTP/AVP;unicast;client_port=60432-60433
                                                                                                    Session: 1185d20035702ca
2023-11-13 18:23:10.574 30060-30620 ServerCommandManager    com.pedro.sample                     I  Audio ports: [60432, 60433]
2023-11-13 18:23:10.575 30060-30620 ServerCommandManager    com.pedro.sample                     I  Audio ports: [60432, 60433]
2023-11-13 18:23:10.575 30060-30620 Client                  com.pedro.sample                     I  RTSP/1.0 200 OK
                                                                                                    Server: pedroSG94 Server
                                                                                                    Cseq: 5
                                                                                                    Content-Length: 0
                                                                                                    Transport: RTP/AVP/UDP;unicast;destination=192.168.0.146;client_port=60432-60433;server_port=5004-5005;mode=play
                                                                                                    Session: 1185d20035702ca
                                                                                                    Cache-Control: no-cache
2023-11-13 18:23:10.580 30060-30620 CommandsManager         com.pedro.sample                     I  PLAY 192.168.0.158:1935/ RTSP/1.0
                                                                                                    CSeq: 6
                                                                                                    User-Agent: LibVLC/3.0.19 (LIVE555 Streaming Media v2016.11.28)
                                                                                                    Session: 1185d20035702ca
                                                                                                    Range: npt=0.000-
2023-11-13 18:23:10.581 30060-30620 Client                  com.pedro.sample                     I  RTSP/1.0 200 OK
                                                                                                    Server: pedroSG94 Server
                                                                                                    Cseq: 6
                                                                                                    Content-Length: 0
                                                                                                    RTP-Info: url=rtsp://192.168.0.158:1935/streamid=0;seq=1;rtptime=0,url=rtsp://192.168.0.158:1935/streamid=1;seq=1;rtptime=0
                                                                                                    Session: 1185d20035702ca
2023-11-13 18:23:10.581 30060-30620 Client                  com.pedro.sample                     I  Protocol UDP
2023-11-13 18:23:10.583 30060-30620 TrafficStats            com.pedro.sample                     D  tagSocket(182) with statsTag=0xffffffff, statsUid=-1
2023-11-13 18:23:10.583 30060-30620 TrafficStats            com.pedro.sample                     D  tagSocket(185) with statsTag=0xffffffff, statsUid=-1
2023-11-13 18:23:10.584 30060-30620 TrafficStats            com.pedro.sample                     D  tagSocket(187) with statsTag=0xffffffff, statsUid=-1
2023-11-13 18:23:10.585 30060-30620 TrafficStats            com.pedro.sample                     D  tagSocket(189) with statsTag=0xffffffff, statsUid=-1
2023-11-13 18:23:10.603 30060-30060 Compatibil...geReporter com.pedro.sample                     D  Compat change id reported: 147798919; UID 10269; state: ENABLED
2023-11-13 18:23:10.609 30060-30621 BaseRtpSocket           com.pedro.sample                     I  wrote packet: Audio, size: 278, port: 60432
```

Can you get it from the logcat to check the difference and possible errors?
I'm using the app sample to do it

**Comment by gushangzao007** [comment]
> got the same error. "Cseq: 0,cSeq not found", What is the Cseq? [Logfile.txt](https://github.com/pedroSG94/RTSP-Server/files/13337174/Logfile.txt)

actually, this "Logfile.txt" is all I can get from the logcat window. 
this log records the whole procedure of the test like:
1.launch app
2.start RTSP server at smart phone
3.use remote VCL player to connect RTSP server
4.RTSP server throws the exception
5.connection broke down.

**Comment by gushangzao007** [comment]
Up to now, I found the key reason is my request value has lost some required information, especially for streamid, so it throw the error when it call function getTrack. 

i'll go further to figure it out why

**Comment by gushangzao007** [comment]
Good News! Root Cause is that the newest VLC Player does not support IPv6 URL. so, I try again with the PotPlayer, it works!
May be This issue could be closed。

New BING with GPT-4 told me that：

> The VLC player uses live555 as its RTSP demuxer, but currently, live555 does not support IPv6. This might be the reason why you’re missing the OPTIONS and DESCRIBE commands when you try to play a remote RTSP video using an IPv6 address.
> As for how to solve this problem, you might need to find an RTSP demuxer that supports IPv6, or look for another player that supports IPv6. For example, some users have found that players like PotPlayer and RedStar can normally play live sources from IPv6.

**Comment by gushangzao007** [comment]
Thank you for your guidance!

**Comment by pedroSG94** [comment]
Hello,

I'm glad that it is working.
If you can create a PR with your solution to integrate it in the project by default it would be great. I will update the PR with necessary changes if need, you don't need to worry about it.

**Comment by gushangzao007** [comment]
ok, my pleasure!
