### ISSUE TITLE
Always fail when compile RTSP server

### ISSUE THREAD

**Issue by swFan** [pedroSG94/RTSP-Server#105]
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform library-2.3.0.aar (com.github.pedroSG94.RootEncoder:library:2.3.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not find library-2.3.0.aar (com.github.pedroSG94.RootEncoder:library:2.3.0).
        Searched in the following locations:
            https://jitpack.io/com/github/pedroSG94/RootEncoder/library/2.3.0/library-2.3.0.aar

**Comment by swFan** [comment]
if use 2.3.2 version, AS compile will fail: 

> Task :app:compileDebugKotlin
e: file:///C:/Users/shrd/Desktop/RTSP-Server-master/app/src/main/java/com/pedro/sample/CameraDemoActivity.kt:15:29 Unresolved reference: ConnectCheckerRtsp
e: file:///C:/Users/shrd/Desktop/RTSP-Server-master/app/src/main/java/com/pedro/sample/CameraDemoActivity.kt:23:49 Unresolved reference: ConnectCheckerRtsp
e: file:///C:/Users/shrd/Desktop/RTSP-Server-master/app/src/main/java/com/pedro/sample/CameraDemoActivity.kt:50:25 Cannot access class 'com.pedro.rtsp.utils.ConnectCheckerRtsp'. Check your module classpath for missing or conflicting dependencies
e: file:///C:/Users/shrd/Desktop/RTSP-Server-master/app/src/main/java/com/pedro/sample/CameraDemoActivity.kt:50:70 Type mismatch: inferred type is CameraDemoActivity but ConnectCheckerRtsp was expected
e: file:///C:/Users/shrd/Desktop/RTSP-Server-master/app/src/main/java/com/pedro/sample/CameraDemoActivity.kt:54:3 'onNewBitrateRtsp' overrides nothing
e: file:///C:/Users/shrd/Desktop/RTSP-Server-master/app/src/main/java/com/pedro/sample/CameraDemoActivity.kt:58:3 'onConnectionSuccessRtsp' overrides nothing
e: file:///C:/Users/shrd/Desktop/RTSP-Server-master/app/src/main/java/com/pedro/sample/CameraDemoActivity.kt:64:3 'onConnectionFailedRtsp' overrides nothing
e: file:///C:/Users/shrd/Desktop/RTSP-Server-master/app/src/main/java/com/pedro/sample/CameraDemoActivity.kt:73:3 'onConnectionStartedRtsp' overrides nothing
e: file:///C:/Users/shrd/Desktop/RTSP-Server-master/app/src/main/java/com/pedro/sample/CameraDemoActivity.kt:76:3 'onDisconnectRtsp' overrides nothing
e: file:///C:/Users/shrd/Desktop/RTSP-Server-master/app/src/main/java/com/pedro/sample/CameraDemoActivity.kt:82:3 'onAuthErrorRtsp' overrides nothing
e: file:///C:/Users/shrd/Desktop/RTSP-Server-master/app/src/main/java/com/pedro/sample/CameraDemoActivity.kt:91:3 'onAuthSuccessRtsp' overrides nothing

**Comment by pedroSG94** [comment]
Hello,

I solved the problem using library version 2.3.0. Try again
Library 2.3.2 compile correctly but has changes that I need to implement in the project for that reason you have that error.
