### ISSUE TITLE
Content-Base missing rtsp:// prefix

### ISSUE THREAD

**Issue by cleancoderob** [pedroSG94/RTSP-Server#108]
I'm trying to get MediaMtx working with the RTSP-Server.  Seems MediaMtx is rather strict with the `Content-Base` attribute of the SDP, and it is rejecting the connection with the RTSP-Server because there is no `rtsp://` prefix.

Details are provided here: https://github.com/bluenviron/mediamtx/issues/825

**Comment by pedroSG94** [comment]
Closing as solved in https://github.com/pedroSG94/RTSP-Server/pull/109
