### ISSUE TITLE
How to show video preview on two separate SurfaceView...?

### ISSUE THREAD

**Issue by ankitda30** [pedroSG94/RTSP-Server#11]
Hi Pedro,
Thank you for huge response...
I'm trying to get two video preview using surfaceview 
I have used

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="horizontal">

        <SurfaceView
            android:layout_weight="1"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:id="@+id/surfaceVw"/>

        <SurfaceView
            android:layout_weight="1"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:id="@+id/surfaceView2"/>

    </LinearLayout>

when I start application only left side surfaceview shows the camera preview and right side shows only black screen....

Please help and guide me how to achieve it....

**Comment by pedroSG94** [comment]
With camera1 You can't do it without opengl and I can't explain you without know opengl.
With camera2 you can use opengl or set other surface to this list (this last is not recommended because could produce fps problems depend of the device):
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.java#L112
You should set this surface the constructor like I do in camera2:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.java#L83
Simply add here a surfaceview and add that surface like I do with the other surfaceview.

**Comment by ankitda30** [comment]
Yes, I have used camera2 using Using RtspServerCamera2.kt
I do tried above changes but I wont show video using surfaceView...
Left side surfaceview does show video preview but right side surfaceview wont show any data...
Could you please make above changes just for demo purpose for me please...?

Below are my changes....

1. RtspServerCamera2.kt class

constructor(surfaceView: SurfaceView,surfaceView2: SurfaceView, connectCheckerRtsp: ConnectCheckerRtsp, port: Int)
          : super(surfaceView) {
    rtspServer = RtspServer(surfaceView.context, connectCheckerRtsp, port)
}

2.Camera2ApiManager class


  public void prepareCamera(SurfaceView surfaceView,SurfaceView surfaceView2  ,Surface surface) {
      this.surfaceView = surfaceView;
      this.surfaceView2 = surfaceView2;
      this.surfaceEncoder = surface;
    prepared = true;
  }

3.Added the view

  final List<Surface> listSurfaces = new ArrayList<>();
      Surface preview = addPreviewSurface();
      if (preview != null) listSurfaces.add(preview);
      if (surfaceEncoder != null) listSurfaces.add(surfaceEncoder);
        listSurfaces.add(surfaceView2.getHolder().getSurface());

4.Camera2Base class


  public Camera2Base(SurfaceView surfaceView,SurfaceView surfaceView2) {
    this.surfaceView = surfaceView;
    this.surfaceView2 = surfaceView2;
    this.context = surfaceView.getContext();
    init(context);
  }

**Comment by ankitda30** [comment]
> With camera1 You can't do it without opengl and I can't explain you without know opengl.
> With camera2 you can use opengl or set other surface to this list (this last is not recommended because could produce fps problems depend of the device):
> https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.java#L112
> You should set this surface in the constructor like I do in camera2:
> https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.java#L83
> Simply add here a surfaceview and add that surface like I do with the other surfaceview.

OMG It works.....
Thanks a lot Pedro.....

**Comment by ankitda30** [comment]
Hi Pedro,
I have created two video preview but when I apply setZoom function then It apply on both the video preview....
What should I need to do so I can zoom on separate video preview....
I have used SurfaceView....
Please help....!

**Comment by navy522** [comment]
> Yes, I have used camera2 using Using RtspServerCamera2.kt I do tried above changes but I wont show video using surfaceView... Left side surfaceview does show video preview but right side surfaceview wont show any data... Could you please make above changes just for demo purpose for me please...?
> 
> Below are my changes....
> 
> 1. RtspServerCamera2.kt class
> 
> constructor(surfaceView: SurfaceView,surfaceView2: SurfaceView, connectCheckerRtsp: ConnectCheckerRtsp, port: Int) : super(surfaceView) { rtspServer = RtspServer(surfaceView.context, connectCheckerRtsp, port) }
> 
> 2.Camera2ApiManager class
> 
> public void prepareCamera(SurfaceView surfaceView,SurfaceView surfaceView2 ,Surface surface) { this.surfaceView = surfaceView; this.surfaceView2 = surfaceView2; this.surfaceEncoder = surface; prepared = true; }
> 
> 3.Added the view
> 
> final List listSurfaces = new ArrayList<>(); Surface preview = addPreviewSurface(); if (preview != null) listSurfaces.add(preview); if (surfaceEncoder != null) listSurfaces.add(surfaceEncoder); listSurfaces.add(surfaceView2.getHolder().getSurface());
> 
> 4.Camera2Base class
> 
> public Camera2Base(SurfaceView surfaceView,SurfaceView surfaceView2) { this.surfaceView = surfaceView; this.surfaceView2 = surfaceView2; this.context = surfaceView.getContext(); init(context); }

Hi @ankitda30 
Were you able to see video preview on both the SurfaceView by using this code?
