### ISSUE TITLE
How to stream the surface of device instead of Camera

### ISSUE THREAD

**Issue by Mahdi-RH** [pedroSG94/RTSP-Server#111]
I want to stream the surface of my device instead of the Camera. I have no idea how to do it. Any help would be appreciated.

**Comment by pedroSG94** [comment]
Hello,

You can use RtspServerDisplay to do it. The usage is really similar to:
https://github.com/pedroSG94/RootEncoder/tree/master/app/src/main/java/com/pedro/streamer/displayexample
The only difference is that you need call startStream without params instead of use url

**Comment by Mahdi-RH** [comment]
Thank you for helping me. I just implemented it and it works well. but there are two problems. First, when I start streaming the surface of my device and play it with a VLC media player on another device it casts the voice of the environment by the speaker as well. I just want to cast the voice of the device(in case of playing music or video).
Second, the quality of screencasting is very low how I can improve it?

**Comment by pedroSG94** [comment]
Hello,

Stream quality depend of the video bitrate and in case of stream the screen you need increment dpi to the device dpi. You can get your device dpi like this:
```java
getResources().getDisplayMetrics().densityDpi
```
bitrate and dpi must be set in prepareVideo method.

About the audio. You can capture audio by 2 ways:
- [Microphone](https://github.com/pedroSG94/RootEncoder/blob/master/library/src/main/java/com/pedro/library/base/DisplayBase.java#L217): This capture audio from your microphone. Mainly used for environment audio but if you have the device reproducing audio your microphone could capture it too.
- [Internal](https://github.com/pedroSG94/RootEncoder/blob/master/library/src/main/java/com/pedro/library/base/DisplayBase.java#L237): This capture the audio of the device and it is only available with Android 9+

**Comment by Mahdi-RH** [comment]
Thank you again. I used the Internal way for audio streaming. Although it works well for playing music by a music player on an Android device, when I go online and play online music on a web page it doesn't work.

**Comment by Mahdi-RH** [comment]
I appreciate your instant response. Last question, how I can calculate the bitrate of my screen to set it in the prepareVideo method?

**Comment by pedroSG94** [comment]
The video bitrate is calculated depend of the resolution selected. You have a guide here:
https://support.google.com/youtube/answer/2853702?hl=en

**Comment by Mahdi-RH** [comment]
All right. Thank you again.

**Comment by Mahdi-RH** [comment]
All right. Thank you again.
