### ISSUE TITLE
Is the CameraX supported for RTSPServer ?

### ISSUE THREAD

**Issue by ronaldsampaio** [pedroSG94/RTSP-Server#113]
i'm finding some difficulties using RTSPServerCamera2. Is there already a support for CameraX? 
If not what is the path to implement using RTSPServerCamera2? How should I create the OpenGLView? 
I tried using PreviewView and passing the context to the RTSPServerCamera2 but 
` video info is null ` 
is the error shown.

**Comment by pedroSG94** [comment]
Hello,

You can support cameraX using VideoSource exactly as you did with usb camera. But in this case you have the VideoSource already developed here:
https://github.com/pedroSG94/RootEncoder/blob/master/app/src/main/java/com/pedro/streamer/rotation/CameraXSource.kt
Dependencies:
https://github.com/pedroSG94/RootEncoder/blob/master/app/build.gradle.kts#L46

**Comment by ronaldsampaio** [comment]
Yeah I remember this implementation. But when trying to use the CameraXSource class it wasn't available for me. Is this some dependency problem?
I'm currently using 
´ implementation 'com.github.pedroSG94.RootEncoder:library:1627f7f62b' ` as version

**Comment by pedroSG94** [comment]
> This is not part of the lib? The ideia is that I could copy this class and implement by my own?

Exactly, you need copy the class. It is not part of the library
