### ISSUE TITLE
Issue downloading gradle dependencies 1.2.8 

### ISSUE THREAD

**Issue by salabogdan** [pedroSG94/RTSP-Server#119]
@pedroSG94 
 These gradle dependencies are no longer available for download.  
```
 implementation 'com.github.pedroSG94:RTSP-Server:1.2.7'
```
The error:

Could not find com.github.pedroSG94:RTSP-Server:1.2.7
  Searched in following locations:
    - https://dl.google.com/dl/android/maven2/com/github/pedroSG94/RTSP-Server/127/RTSP-Server-1.2.7.pom
    - https://repo.maven.apache.org/maven2/com/github/pedroSG94/RTSP-Server/127/RTSP-Server-1.2.7.pom
    - https://jitpack.io/github/pedroSG94/RTSP-Server/127/RTSP-Server-1.2.7.pom

If you previously downloaded these dependencies you will need to clear all the .gradle/caches/

I have tried with all `1.2.x ` versions and nothing works.

**Comment by pedroSG94** [comment]
Hello,

I recompiled version 1.2.7. Version 1.2.8 should work too.

I'm recompiling others versions

**Comment by pedroSG94** [comment]
The version 1.2.8 is not compiling correctly (apparently compiled but the arr to download is not available) so I created version 1.2.9 and it is working fine now.

Closing the issue as solved
