### ISSUE TITLE
Unable to resolve in gradle old commits in projectsa

### ISSUE THREAD

**Issue by RelioXx** [pedroSG94/RTSP-Server#120]
Hi i am trying to replicate a very similar use case that was opened in https://github.com/pedroSG94/RTSP-Server/issues/110 

For that i am building my project with the commits that you mentioned in the issue:
    implementation 'com.github.pedroSG94:RTSP-Server:7469cdcb78'
    implementation 'com.github.pedroSG94.RootEncoder:library:1627f7f62b' 

But when trying to sync gradle is failing to resolve those commits, Do you know what I might be doing incorrectly?

![image](https://github.com/pedroSG94/RTSP-Server/assets/38957658/0a85e488-08cd-4dc9-b357-28a07c710f13)

**Comment by pedroSG94** [comment]
Hello,

That feature is available in the last version.
Try to compile the library using last version in the readme.
