### ISSUE TITLE
How to take photo?

### ISSUE THREAD

**Issue by b0iq** [pedroSG94/RTSP-Server#122]
Dear @pedroSG94  and other maintainers,

I found an issue in this amazing library.
the issue is I want to take photo from the current stream I tried: 
```kt
Rtsp.rtsp.glInterface?.takePhoto {
//..
}
```
it working fine for first call only. the second call it **crashes** the app

**Comment by pedroSG94** [comment]
Hello, can you share the crash log?

**Comment by b0iq** [comment]
Sorry the crash caused by react native view manager. not by this library
