### ISSUE TITLE
Not able to Crop video frame using CropYuv....? Please help...!

### ISSUE THREAD

**Issue by ankitda30** [pedroSG94/RTSP-Server#13]
Hi Pedro,
As you told on your last reply frame cropping can be done on Video Encoder

https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java#L264.

I do make following changes in VideoEncoder
on 

getInputFrame
{
  buffer = isYV12 ? YUVUtil.YV12toYUV420byColor(buffer, width, height, formatVideoEncoder)
                      : YUVUtil.NV21toYUV420byColor(buffer, width, height, formatVideoEncoder);

      buffer = **YUVUtil.CropYuv(MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV420SemiPlanar,buffer,width,height,600,400);**

}

My camera resolution is 640*480 
but still no frame cropping effect has been found.... 

Please Please help...

**Comment by pedroSG94** [comment]
I told you that you can't crop with SurfaceView and Camera2 because it is **ONLY for camera1 with SurfaceView**. Also if you do that, only stream result is affected (no effect in preview).

**Comment by ankitda30** [comment]
> I told you that you can't crop with SurfaceView and Camera2 because it is **ONLY for camera1 with SurfaceView**. Also if you do that, only stream result is affected (no effect in preview).

I'm using camera1 now....
I wanted to crop only stream now using camera1
I understand preview functionality...
my camera resolution is 640*480 as default
Please tell me how to crop stream using YUVUtil.crop....
It's heartful request....
Did i missed something in while using this command ...?

**Comment by pedroSG94** [comment]
You can use OpenGlView to crop preview and/or stream result. If you only want crop a view (and no both) add a surfaceView to openglview constructor in camera2apimanager like you did with surfaceview:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.java#L100

**Comment by pedroSG94** [comment]
I'm really confuse. 
You can't use 2 preview with camera1 but you want crop with camera1.
Want do you want exactly?:
- 2 preview and crop 1 preview
- 2 preview and crop stream result
- 2 preview and crop both preview
- 1 preview and crop preview
- 1 preview and crop stream result
- 1 preview and crop preview and stream result

**Comment by ankitda30** [comment]
**2 preview and crop stream result**

Could you please help me....?

**Comment by pedroSG94** [comment]
Ok. In this case you have 2 ways:
- Use 2 OpenGlView with keepaspectratio parameter to true and change this line to crop stream result:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/utils/gl/PreviewSizeCalculator.java#L32
I told you [here](https://github.com/pedroSG94/RTSP-Server/issues/10). What means that line
- Crop with VideoEncoder using this lines (Remember change values as you want):
```java
videoFormat.setInteger("crop-left", 0);
videoFormat.setInteger("crop-top", 0);
videoFormat.setInteger("crop-right", 0);
videoFormat.setInteger("crop-bottom", 0);
```
You can add it here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java#L117
Documentation:
https://developer.android.com/reference/android/media/MediaCodec#data-types

**Comment by ankitda30** [comment]
I'm facing problem with 2 OpenGlView please guide me with it...
How to set 2 OpenGlView as you told with same as SurfaceVIew...

**Comment by ankitda30** [comment]
> I'm really confuse.
> You can't use 2 preview with camera1 but you want crop with camera1.
> What do you want exactly?:
> 
> * 2 preview and crop 1 preview
> * 2 preview and crop stream result
> * 2 preview and crop both preview
> * 1 preview and crop preview
> * 1 preview and crop stream result
> * 1 preview and crop preview and stream result

Hi Pedro,
I wanted to crop the region of the stream using camera1...
please tell me how to use YUVCrop function...
It gives arrayoutbound error when I pass destination width and height...
Please Please help....

**Comment by ankitda30** [comment]
> Ok. In this case you have 2 ways:
> 
> * Use 2 OpenGlView with keepaspectratio parameter to true and change this line to crop stream result:
>   https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/utils/gl/PreviewSizeCalculator.java#L32
>   I told you [here](https://github.com/pedroSG94/RTSP-Server/issues/10). What means that line
> * Crop with VideoEncoder using this lines (Remember change values as you want):
> 
> ```java
> videoFormat.setInteger("crop-left", 0);
> videoFormat.setInteger("crop-top", 0);
> videoFormat.setInteger("crop-right", 0);
> videoFormat.setInteger("crop-bottom", 0);
> ```
> 
> You can add it here:
> https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java#L117
> Documentation:
> https://developer.android.com/reference/android/media/MediaCodec#data-types

Thanks a lot Pedro...
I have tried all the changes you told by using crop in encoder

  videoFormat.setInteger("crop-left", 0);
      videoFormat.setInteger("crop-top", 0);
      videoFormat.setInteger("crop-right", -50);
      videoFormat.setInteger("crop-bottom", -100);

but I found nothing has been changed in my preview as well on my stream results....
Could you please check it on your side and tell me how to crop region....?
I wanted to crop only half region of the stream result...

**Comment by ankitda30** [comment]
> Hi Pedro,
> As you told on your last reply frame cropping can be done on Video Encoder
> 
> https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java#L264.
> 
> I do make following changes in VideoEncoder
> on
> 
> getInputFrame
> {
> buffer = isYV12 ? YUVUtil.YV12toYUV420byColor(buffer, width, height, formatVideoEncoder)
> : YUVUtil.NV21toYUV420byColor(buffer, width, height, formatVideoEncoder);
> 
> ```
>   buffer = **YUVUtil.CropYuv(MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV420SemiPlanar,buffer,width,height,600,400);**
> ```
> 
> }
> 
> My camera resolution is 640*480
> but still no frame cropping effect has been found....
> 
> Please Please help...

By making YUVCrop I always got 
java.lang.IndexOutOfBoundsException:

this error....dont know why...
Please explain....
