### ISSUE TITLE
2-Second Delay in Stream Broadcasting

### ISSUE THREAD

**Issue by savuerka** [pedroSG94/RTSP-Server#132]
Good day! Thank you for the wonderful project. Could you please help me solve the following issue: When connecting to the stream (using VLC), everything works as expected, but from the very first seconds, a 2-second delay occurs in the broadcast.

**Comment by pedroSG94** [comment]
Hello,

VLC has delay, I can't do anything about it.
You can use ffmpeg to reproduce the stream using a config to reduce delay.

```
ffplay -fflags nobuffer rtsp://192.168.0.158:1935/
```

You can replace the stream URL with the URL used in VLC

**Comment by savuerka** [comment]
Thank you for your response, I will try this solution.
