### ISSUE TITLE
why rtsp protocol with TCP has rtmp in it,and vlc can't resolve this rtmp

### ISSUE THREAD

**Issue by intmainwjj** [pedroSG94/RTSP-Server#15]
![image](https://user-images.githubusercontent.com/20499697/79114584-37171180-7db6-11ea-9dcb-dc0399040667.png)

**Comment by intmainwjj** [comment]
112587	262.337168	192.168.1.92	192.168.1.91	RTMP	1522	Unknown (0x0)
112588	262.337169	192.168.1.92	192.168.1.91	TCP	1522	1935 → 51359 [ACK] Seq=40056131 Ack=7153 Win=1425 Len=1448 TSval=8609414 TSecr=767266634
112590	262.337172	192.168.1.92	192.168.1.91	RTMP	1522	Unknown (0x0)

**Comment by pedroSG94** [comment]
What endpoint are you using with VLC?

**Comment by intmainwjj** [comment]
I use mac VLC and wireshark capture package，and found rtmp protocol as show above

**Comment by intmainwjj** [comment]
is this rtmp protocol may be tcp?but something is wrong.
VLC play rtsp stream looks normal

**Comment by pedroSG94** [comment]
I don't know the reason but I only use RTP (not RTMP) packets and RTSP commands.
TCP protocol is used with Java socket API.
