### ISSUE TITLE
Change the resolution width and height

### ISSUE THREAD

**Issue by shintabmt** [pedroSG94/RTSP-Server#16]
Hi @pedroSG94 ,
In my case, i start the server in mobile with 
`if (rtspServerDisplay.prepareVideo() && rtspServerDisplay.prepareAudio()){
rtspServerDisplay.startStream()
}`
so how can i adjust the video solution, due to my client request?

Please help

**Comment by pedroSG94** [comment]
If you want change resolution you can use this method:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L211
If you want change resolution according with client. You should create a way to communicate it for example with a socket.

**Comment by shintabmt** [comment]
Thanks @pedroSG94 for replying me,

> If you want change resolution according with client. You should create a way to communicate it for example with a socket.
Already did it
i already use this method, for example, i start stream with resolution 640*480, but when i try to change the using above method to 1280 *720, i saw nothing change

**Comment by pedroSG94** [comment]
```java
prepareVideo(int width, int height, int fps, int bitrate, int rotation, int dpi)
```
Example (1280x720, 30fps, 5Mb/s):
```java
preapreVideo(1280, 720, 30, 5000 * 1024, 0, 320)
```

**Comment by shintabmt** [comment]
Yes, i used this method as well. But in my case is:
- I start stream with resolution
`prepareVideo(640, 480, 30, 1200 * 1024, 0, 320)`
- My client side need to view with higher resolution, and call to my server.
- Then i use this method 
`prepareVideo(1280, 720, 30, 5000 * 1024, 0, 320)`
But the resolution is not change. Do i need to stop and start server ?

**Comment by pedroSG94** [comment]
Yes, You need stop and start server to change resolution.

**Comment by shintabmt** [comment]
do we have another way to do it ?

**Comment by pedroSG94** [comment]
No for now

**Comment by shintabmt** [comment]
thanks @pedroSG94
