### ISSUE TITLE
It is possible to access through Ethernet 

### ISSUE THREAD

**Issue by meduar** [pedroSG94/RTSP-Server#18]
Hi
I have a Samsung galaxy s9 that connects to the internet through an ethernet adapter when I start the rstp server it doesnt work and it shows ip 0.0.0.0 although the phone has an IP and I can browse the internet, if I turn on the wifi it works.

**Comment by pedroSG94** [comment]
I never tried with a ethernet adapter and I haven't an adapter to test it (maybe getIp method is working bad) but this should work if you know your IP. Try get your ip with adb:
```
adb shell ip -o a
```
About use cellular network normally your telecom provider block port and you can't open it for this reason you can't communicate with it. You have a post related with this here:
https://stackoverflow.com/questions/46669572/unable-to-connect-android-socket-connection-over-cellular-network

**Comment by pedroSG94** [comment]
I did an update for getIp method. Now, this should show you cellular network ip properly and maybe your ethernet adapter (I can't test it let me know if this is working):
https://github.com/pedroSG94/RTSP-Server/commit/ddc1e2d57920735a2d1076345d2fee1c33688659
