### ISSUE TITLE
Stream frames mixing issues while streaming two rtsp servers....

### ISSUE THREAD

**Issue by ankitda30** [pedroSG94/RTSP-Server#19]
Hi,
My device supports two camera preview at same time (front and back)
I made following changes with different names

1. Created another RtspServerCamera class
2. Created another Camera1Base class to open front camera
3. Created another RtspServer with different port number

When I click on start stream It does show two camera preview 
when I entered rtsp with different port url into vlc media player / browser it starts streaming but mixes the the video data and shows output like front and back camera data stream into one  url...
Don't know how to fix issues 
Please help......

**Comment by pedroSG94** [comment]
What do you want exactly?
Stream both cameras at same time in an endpoint?
Stream both cameras in different endpoint?

**Comment by ankitda30** [comment]
I want Stream both cameras (Front and Back) in different endpoint?
I did achieved output but facing frame mixing issue

**Comment by ankitda30** [comment]
> I want Stream both cameras (Front and Back) in different endpoint?
> I did achieved output but facing frame mixing issue

I made following changes in CameraDemoActivity for different streams with different endpoint...
            rtspServerCamera1 = RtspServerCamera1(surfaceView, this, 1935)
            surfaceView.holder.addCallback(this)

        rtspServerCameraNew = RtspServerCameraNew(surfaceView2, this, 1936)
            surfaceView2.holder.addCallback(this)

**Comment by pedroSG94** [comment]
If you haven't problems with microphone that should work. If you have problems with it try select different microphone for both ([try with CAMCORDER and MIC values, one on each server](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/audio/MicrophoneManager.java#L60)) and startPreview directly with front and back camera to avoid problems with cameras.

Can you share a logcat to know if both player is connected to both server or what is happens?
