### ISSUE TITLE
loss latest frame

### ISSUE THREAD

**Issue by shintabmt** [pedroSG94/RTSP-Server#2]
I implemented the rtsp display server to stream my screen. I disable the sound also. But i lose some frame. Tested with VLC the latest frame does not update until i doing something in my android screen.

**Comment by pedroSG94** [comment]
This isn't a bug. MediaProjectionManager API of android never render a frame if you are not doing something in your screen:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/63

**Comment by shintabmt** [comment]
thanks @pedroSG94, i see what happened
