### ISSUE TITLE
After about a minute, the audio stream will stop

### ISSUE THREAD

**Issue by mafanwei** [pedroSG94/RTSP-Server#20]
I found this library very useful and solved a lot of my problems. 
I am experiencing problems with audio playback stopping. 

I am using ‘RtspServerDisplay.prepareAudio()’ and ‘RtspServerDisplay.prepareVideo()’ to play with ‘ffplay’ on another device, is my parameter setting incorrect?

thank you very much.

**Comment by pedroSG94** [comment]
Can you share a logcat when you experiment audio stop?

**Comment by mafanwei** [comment]
I found the problem because of the audio recording process being killed by Android. 
How should I improve it?

**Comment by pedroSG94** [comment]
Are you using a service? That could be related with that.
Other reason could be that your device stop microphone if it is used in background for battery. Try go to settings - apps and disable battery optimization.
