### ISSUE TITLE
Video Frames getting disturbances or not clear while opening the rtsp link through VLC

### ISSUE THREAD

**Issue by rishabhtech1** [pedroSG94/RTSP-Server#24]
I am using the RTSP server inside my application and after starting the server i can see that there is a **lot of distortion/disturbances in the frames** from the rtsp link when i am opening it from the VLC Player. 

**### Frames are breaking and hence there is a disturbances in the video that is appearing.**

Please help me with the probable solution for this issue and why is this happening???

Thank you in advance.

**Comment by pedroSG94** [comment]
- Did you tried use OpenGlView instead of SurfaceView?
- Can you share an image to know what do you mean with distortion/disturbances?

**Comment by rishabhtech1** [comment]
I was trying with the  Surface View, but the phone's camera view is alright. But when in an watching the stream using VLC with the rtsp link generated than the image in stream is getting disturbed.

I have attached the screen shot below for reference. Please check.

Thank you so much for such a quick response. Kindly help me with this issue. 

Regards,

![8w5pN](https://user-images.githubusercontent.com/68075045/99413415-c28fec80-291b-11eb-95a2-077ce2227054.jpg)

**Comment by pedroSG94** [comment]
I was testing with your configuration but I can’t reproduce your case.
If you don’t need support for api 16 and api 17 I suggest you use Openglview that get better performance.
Can you share me device model and api used in your case?
