### ISSUE TITLE
Error while using Camera2Base

### ISSUE THREAD

**Issue by wlxyhy** [pedroSG94/RTSP-Server#25]
the codes are:
`camera2Base.prepareVideo();  `
and then 
`camera2Base.startStream(url);`
but I come up with NPE, the reason is audioEncoder.codec is null for I don't prepare audio,
Must I prepare both video and audio?

After I prepared audio, there's another problem: 
java.lang.IllegalStateException: startRecording() called on an uninitialized AudioRecord.

How to solve it?

**Comment by pedroSG94** [comment]
You must prepareAudio and check if both methods (prepareVideo and prepareAudio) return true to call startStream.

**Comment by wlxyhy** [comment]
Thank you, is there any help-documents?
