### ISSUE TITLE
How to reduce the time delay

### ISSUE THREAD

**Issue by wlxyhy** [pedroSG94/RTSP-Server#27]
There's a time delay of about 1-2 seconds, is there any way to reduce it? 
I tried a web camera with almost no video delay at all, perhaps less than 200ms, it's also by RTSP.

**Comment by p-try** [comment]
Do you use VLC to display the stream? I had the same problem when I used VLC for tests. But once I switched [to this RTSP client library](https://github.com/alexeyvasilyev/rtsp-client-android) (which was what I had in mind anyway) the stream was very smooth. So I believe VLC's buffering system must be responsible for the delay.
