### ISSUE TITLE
Error when linking against rtplibrary 1.9.6: superclass is declared final

### ISSUE THREAD

**Issue by p-try** [pedroSG94/RTSP-Server#28]
When I upgrade to rtplibrary 1.9.6 I run into the following error:

`java.lang.VerifyError: Superclass com.pedro.rtsp.rtsp.CommandsManager of com.pedro.rtspserver.ServerCommandManager is declared final`

Version 1.9.3 is working, though.

**Comment by dukess** [comment]
Same trouble with rtplibrary 1.9.7. Android 7.1.2

**Comment by pedroSG94** [comment]
Fixed. Compile last gradle version of readme
