### ISSUE TITLE
Need help regarding h265 video encode....!

### ISSUE THREAD

**Issue by ankitda30** [pedroSG94/RTSP-Server#3]
Hi,
I'm new in RTSP server application I'm able to connect,stream and record video into h264 video encode format but I need to record video into h265 video encode format.
I'm new in kotlin and I don't understand when this method should I use so I can set video codec to H265 after recording the video....

  **fun setVideoCodec(videoCodec: VideoCodec) {
    videoEncoder.type =
      if (videoCodec == VideoCodec.H265) CodecUtil.H265_MIME else CodecUtil.H264_MIME
  }**

**Please help.......!**

**Comment by ankitda30** [comment]
Hi,
I'm able to change the video codec from h264 into h265 by importing the module **rtplibrary** and **encoder**.
Currently I'm able to record video into h265/HEVC format by changing 
**CodecUtil.H264_MIME** into **CodecUtil.H265_MIME** everywhere it used in VideoEncoder java file, but when I click on start stream then I can see the server has been started and audio/video packets  getting exchanged but when I put the auto generated Url on VLC player to see the live streaming then I can hear audio but no visuals shown....

Please help.....

**Comment by pedroSG94** [comment]
You are right, H265 was bugged. I did a fix for it:
https://github.com/pedroSG94/RTSP-Server/commit/deeaf25a8c868bba4bfd446552f587328530e743
Now, you only need replace this line:
https://github.com/pedroSG94/RTSP-Server/blob/master/app/src/main/java/com/pedro/sample/CameraDemoActivity.kt#L43
To:
```java
rtspServerCamera1?.setVideoCodec(VideoCodec.H265)
surfaceView.holder.addCallback(this)
```

**Comment by ankitda30** [comment]
It's working in h265 video codec now....
Thanks a lot..... :)
