### ISSUE TITLE
Licence question

### ISSUE THREAD

**Issue by RogerHardiman** [pedroSG94/RTSP-Server#31]
Hi there
What Licence is your software released under - MIT, Apache or BSD ?

Thanks
Roger
(co-author of the NodeJS RTSP Client library called Yellowstone)
(co-author of the Raspberry Pi ONVIF Library (called RPOS)
(co-author of Sharp RTSP C# library)

**Comment by pedroSG94** [comment]
Hello,

You can use it as Apache licence. I will update it today
