### ISSUE TITLE
ERROR: Failed to resolve: 

### ISSUE THREAD

**Issue by iqiluwxy** [pedroSG94/RTSP-Server#34]
why is the prompt  ERROR: Failed to resolve: com.github.pedroSG94.RTSP-Server:1.0.6:
Affected Modules: app？？？

**Comment by pedroSG94** [comment]
It is working for me.
Did you add maven repository in general build.gradle?
```gradle
allprojects {
		repositories {
			maven { url 'https://jitpack.io' }
		}
	}
```

**Comment by iqiluwxy** [comment]
Yes, I did as required, and I failed to bring in colleagues on his project







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Pedro ***@***.***&gt;; 
发送时间: 2021年4月14日(星期三) 晚上6:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [pedroSG94/RTSP-Server] ERROR: Failed to resolve:  (#34)





 
It is working for me.
 Did you add maven repository in general build.gradle?
 allprojects { 		repositories { 			maven { url 'https://jitpack.io' } 		} 	}

**Comment by iqiluwxy** [comment]
It's settled. Thank you very much
