### ISSUE TITLE
Excuse me? This RTSP-Server Demo，how can I only launch audio without video? Is there any API call?

### ISSUE THREAD

**Issue by iqiluwxy** [pedroSG94/RTSP-Server#35]

**Comment by pedroSG94** [comment]
This is not available for now. I will mark this as feature

**Comment by iqiluwxy** [comment]
OK, thank you for your answer

**Comment by iqiluwxy** [comment]
I'm looking forward to your functions

**Comment by pedroSG94** [comment]
It is available now,  use version 1.0.8:
https://github.com/pedroSG94/RTSP-Server/blob/master/rtspserver/src/main/java/com/pedro/rtspserver/RtspServerOnlyAudio.kt
