### ISSUE TITLE
How to connect from other wifi network?

### ISSUE THREAD

**Issue by ToysoftInc** [pedroSG94/RTSP-Server#36]
HI

The app demo works fine with the same wifi network.
Does this work with mobile network and how to get the public ip address?

thanks

**Comment by pedroSG94** [comment]
It is not possible to open a port in a mobile network (this is a telephony providers cap, nothing to do).
The only way is start it in your local net, configure your router and use your public ip like if you are using a normal server in your local net and you want take access from outside.

**Comment by ToysoftInc** [comment]
thanks
