### ISSUE TITLE
 Could not find com.github.pedroSG94.RTSP-Server:1.0.8

### ISSUE THREAD

**Issue by ToysoftInc** [pedroSG94/RTSP-Server#38]
Not sure what is going on.  I got this error in my demo project

Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.pedroSG94.RTSP-Server:1.0.8:.
     Required by:
         project :app

allprojects {
    repositories {
        jcenter()
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}

dependencies {
    implementation 'com.github.pedroSG94.RTSP-Server:1.0.8'
    implementation 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:2.0.2'
}

**Comment by pedroSG94** [comment]
I did a typo on readme. Fixed, try now:
https://github.com/pedroSG94/RTSP-Server/commit/744014555dd72291d44f8d49813bb78b55362ddc

**Comment by ToysoftInc** [comment]
thanks
