### ISSUE TITLE
How to send commands from VLC player to mobile device...

### ISSUE THREAD

**Issue by ankitda30** [pedroSG94/RTSP-Server#4]
Hi Pedro,
I want to zoom camera from vlc player while streaming.
I'm new in kotlin developement 
I'm not able to understand how **ServerCommandManager.kt** file or commands will work while streaming live video....
And I wants to know what should I need to do to control mobile app camera using commands from vlc player.....

Please help.....!

**Comment by pedroSG94** [comment]
Basically you get a string in this line:
https://github.com/pedroSG94/RTSP-Server/blob/master/rtspserver/src/main/java/com/pedro/rtspserver/RtspServer.kt#L133
After that ServerCommandManager is only a string parser to get important info in that string.

You can create your own class to parse your custom string from vlc and add it to that method

**Comment by ankitda30** [comment]
Yes, You are right...
I just did that and got my own aspected string from the url.

Thanks a lot Perdro......!
