### ISSUE TITLE
How rotate camera 90º clockwise with RtspServerCamera1

### ISSUE THREAD

**Issue by ArqinT** [pedroSG94/RTSP-Server#43]
In OpenGLView camera preview shown rotated 90ª anticlockwise. How can I rotate is back?

**Comment by pedroSG94** [comment]
You can set any rotation in startPreview and/or prepareVideo methods.
Also you can flip openglview vertical and horizontal if needed using this method:
openGlView.setCameraFlip(horizontal, vertical);

**Comment by ArqinT** [comment]
startPreview helped, but for some reason the video is transmitted in landscape mode. How can I make a portrait mode?

**Comment by ArqinT** [comment]
> Thank you! startPreview helped, but for some reason the video is transmitted in landscape mode. How can I make a portrait mode?

Only now the video flips when you start streaming

**Comment by pedroSG94** [comment]
Try use a rotation filter:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L247

**Comment by ArqinT** [comment]
> Try use a rotation filter:
> https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L247

You make my day!

Can I switch audio off on stream?

**Comment by pedroSG94** [comment]
You can use this:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/customexample/RtmpActivity.java#L192
