### ISSUE TITLE
Request to mark "open" classes and methods

### ISSUE THREAD

**Issue by bianchina3** [pedroSG94/RTSP-Server#44]
Hello.
sorry if I repeat the request already made in the past.
The final modifier mark classes and methods as not allowed to be overridden and  In Kotlin this is the default.
I cannot override your classes.
you may want to consider marking your classes with "open"

**Comment by pedroSG94** [comment]
I will do it soon

**Comment by pedroSG94** [comment]
I did an update for it. Try with new library version
