### ISSUE TITLE
Playing over mobile hotspot

### ISSUE THREAD

**Issue by R00iBaard** [pedroSG94/RTSP-Server#47]
Hi there, firstly thanks so much for contribution, it works well.

What we require is having the RTSP server running on the same device that creates the wifi network. Kind of like a GoPro for example, where the users mobile phone will join the wifi network created by the device. 
When we create the mobile hotspot and run the RTSP Server from that device, the client (VLC for now, on windows) connects to this network however the playback doesn't work unless we both connect through an actual router. Is this possible?

**Comment by pedroSG94** [comment]
Hello,

Try to create a hotspot and disable internet access (4G data) to let device only with a network available (hotspot network in this case).
Remember that you need create a ServerSocket in the same network that your hotspot.
I'm creating the ServerSocket here:
https://github.com/pedroSG94/RTSP-Server/blob/master/rtspserver/src/main/java/com/pedro/rtspserver/RtspServer.kt#L45

Try to check IP of server to know if you are in the same network with both devices:
https://github.com/pedroSG94/RTSP-Server/blob/master/rtspserver/src/main/java/com/pedro/rtspserver/RtspServer.kt#L25

**Comment by R00iBaard** [comment]
Great stuff thanks! Its working
