### ISSUE TITLE
How to generate rtsp url by using this RTSP-Server app without using any server like Wowza

### ISSUE THREAD

**Issue by SreeniMannem** [pedroSG94/RTSP-Server#49]
Hi, i am unable to stream using local server url. Whenever i tried with Wowza engine, it will provide "rtsp://ipaddress:port/application/stream_name". As it is a server, please help me in, how to generate the rtsp url to stream to Android mobile.

Kindly do needful.

**Comment by pedroSG94** [comment]
You can't push to this server. Only pull (Reproduce stream with a player) is available.

**Comment by SreeniMannem** [comment]
Thanks for your reply @pedroSG94. Shall we directly stream rtsp, without mediator server (like Wowza)? Or do we have any such servers which can push and pull

**Comment by pedroSG94** [comment]
Yes, normally few players support reproduce camera ip directly. For example VLC. 
You can try this app example:
https://github.com/pedroSG94/vlc-example-streamplayer

This is only an example so I recommend you compile last VLC version if it is working for you.
