### ISSUE TITLE
Two RtspServers

### ISSUE THREAD

**Issue by FunnyDevs** [pedroSG94/RTSP-Server#54]
Hello! Could i start 2 different rtsp servers (with different resolutions)?

**Comment by pedroSG94** [comment]
Unfortunatelly no.
Multiple resolutions are not supported and create more than a microphone/camera at the same time is not possible in Android.

**Comment by FunnyDevs** [comment]
Neither using one server and two different ports? With https://github.com/pedroSG94/rtmp-rtsp-stream-client-java i am able to use two different resolutions (one for streaming and one for recording) creating another encoder

**Comment by pedroSG94** [comment]
> Neither using one server and two different ports? With https://github.com/pedroSG94/rtmp-rtsp-stream-client-java i am able to use two different resolutions (one for streaming and one for recording) creating another encoder

If is possible but require modify the library

**Comment by FunnyDevs** [comment]
Which classes should i modify?

**Comment by pedroSG94** [comment]
If you already modified https://github.com/pedroSG94/rtmp-rtsp-stream-client-java to support 2 resolutions you only need:
- Create a second instance of RtspServer. For example, if you are using Camera1 here:
https://github.com/pedroSG94/RTSP-Server/blob/master/rtspserver/src/main/java/com/pedro/rtspserver/RtspServerCamera1.kt
- Use a different port for that second instance:
https://github.com/pedroSG94/RTSP-Server/blob/master/rtspserver/src/main/java/com/pedro/rtspserver/RtspServerCamera1.kt#L24
- Use it exactly like the first one and send the second videoEncoder buffer and info to the second RtspServer instance (create callbacks of second VideoEncoder and use second RtspServer in that callbacks):
https://github.com/pedroSG94/RTSP-Server/blob/master/rtspserver/src/main/java/com/pedro/rtspserver/RtspServerCamera1.kt#L85
https://github.com/pedroSG94/RTSP-Server/blob/master/rtspserver/src/main/java/com/pedro/rtspserver/RtspServerCamera1.kt#L93

**Comment by FunnyDevs** [comment]
Thank you!
