### ISSUE TITLE
BindException:Address already in use

### ISSUE THREAD

**Issue by hjywyj** [pedroSG94/RTSP-Server#56]
# Exception
java.net.PlainSocketImpl.socketBind(Native Method)
java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:368)
java.net.ServerSocket.bind(ServerSocket.java:377)
java.net.ServerSocket.<init>(ServerSocket.java:237)
java.net.ServerSocket.<init>(ServerSocket.java:128)
com.pedro.rtspserver.RtspServer.z(RtspServer.kt:1)
com.pedro.rtspserver.RtspServer.b(RtspServer.kt)
com.pedro.rtspserver.a.run(Unknown Source)
java.lang.Thread.run(Thread.java:761)

# Mapping
    int port -> b
    void startServer$lambda-1(com.pedro.rtspserver.RtspServer):46:48 -> z
    void startServer$lambda-1(com.pedro.rtspserver.RtspServer):51:51 -> z
    void startServer$lambda-1(com.pedro.rtspserver.RtspServer):53:55 -> z
    void startServer$lambda-1(com.pedro.rtspserver.RtspServer):54:54 -> z
    void startServer$lambda-1(com.pedro.rtspserver.RtspServer):61:61 -> z
    void startServer$lambda-1(com.pedro.rtspserver.RtspServer):58:58 -> z
    void startServer$lambda-1(com.pedro.rtspserver.RtspServer):65:65 -> z

**Comment by hjywyj** [comment]
please add `catch (e:  java.net.BindException)` in RtspServer.startServer

**Comment by pedroSG94** [comment]
Fixed:
https://github.com/pedroSG94/RTSP-Server/commit/f046e93313cdca3d863da67f756e7df695471a08
