### ISSUE TITLE
How to stream video

### ISSUE THREAD

**Issue by janeSmith99221** [pedroSG94/RTSP-Server#58]
I'm trying to stream video from local storage. is there any way to do this.

**Comment by pedroSG94** [comment]
Using a video file?
You can do it with RtspServerFromFile class.
The usage is similar to the example but in this case instead of set parameters to prepareVideo and prepareAudio method, you need set a path.

**Comment by janeSmith99221** [comment]
I don't have any idea to  use RtspServerFromFile class. if you have any example pls tell me.

**Comment by pedroSG94** [comment]
You can use this:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/filestreamexample/RtspFromFileActivity.java
The only difference with this class is that you must use startStream without parameters and in RtspServerFromFile constructor you need indicate a port.
As you can see (mentioned above) It is so similar to app example. The only difference is that prepare method use a path to file.
