### ISSUE TITLE
Failed to resolve: com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:2.1.4

### ISSUE THREAD

**Issue by janeSmith99221** [pedroSG94/RTSP-Server#59]
added     implementation 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:2.1.4'
to the build.gradle.
but still facing Failed to resolve: com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:2.1.4

**Comment by pedroSG94** [comment]
Did you add repository properly?:
```gradle
allprojects {
  repositories {
    maven { url 'https://jitpack.io' }
  }
}
```

If you created the project recently this should be added to settings.gradle file.

**Comment by janeSmith99221** [comment]
> Did you add repository properly?:
> 
> ```groovy-gradle
> allprojects {
>   repositories {
>     maven { url 'https://jitpack.io' }
>   }
> }
> ```
> 
> If you created the project recently this should be added to settings.gradle file.
