### ISSUE TITLE
How to know frame rate and streaming resolution.

### ISSUE THREAD

**Issue by janeSmith99221** [pedroSG94/RTSP-Server#60]
I streamed video successfully through  RtspServerFromFile and I want to know streaming frame rate and resolution.

**Comment by pedroSG94** [comment]
Hello,
The resolution is the video file resolution and the frame rate is cap to video file framerate but you can add a callback that notify you fps:
```java
    rtmpFromFile.setFpsListener(new FpsListener.Callback() {
      @Override
      public void onFps(int fps) {
        
      }
    });
```
If you want you can get video file resolution using android API:
https://stackoverflow.com/questions/8000978/is-it-possible-to-get-the-resolution-of-a-video-in-android/27437526

**Comment by janeSmith99221** [comment]
> 

okay thanks.

**Comment by pedroSG94** [comment]
Hello,

Did you check with others files? 

FPS depend of your file and your device performance.
I'm using a decoder to extract frames from the file and encoding it in H264 so if you have a problem in this proccess (device performance) your fps could change a bit in few moments.

Also, fps callback is an estimation fps but this could change a bit and could add few fps to the next logs depend of the timestamp but if you calculate the average this should be really similar to the real value.
