### ISSUE TITLE
Publish server stream

### ISSUE THREAD

**Issue by FunnyDevs** [pedroSG94/RTSP-Server#61]
Hello pedro! I use the rtsp server to do some manipulations with ffmpeg, but i should need even to publish the stream to a remote wowza server but i can't use ffmpeg because i need the adaptive bitrate of your rtsp client librart (https://github.com/pedroSG94/rtmp-rtsp-stream-client-java).
Could i publish the local rtsp server through the client library?

**Comment by pedroSG94** [comment]
Re stream to another server?
It is not possible because I haven't a way to capture a stream in this library. It is only for push.
If you can find a way to get video and audio data from your server you can use RtspClient or RtmpClient and send it to other server.

**Comment by FunnyDevs** [comment]
I can get the stream with ffmpeg in a pipe(i use this library https://github.com/tanersener/ffmpeg-kit/wiki/Pipe-Support) and read the stream as a standard FileInputStream, but then i don't know to push this stream of bytes to RtspClient.

**Comment by pedroSG94** [comment]
The way to extract raw H264/AAC packets must be developed by yourself (I don't know that library and how to get buffers from that, you should ask in the library issues or study it).
After that, you can follow this issue that explain how to use RtspClient:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/1033#event-5870585859

**Comment by FunnyDevs** [comment]
ok, it works!! Thank you again :)
