### ISSUE TITLE
Correct preview rotation

### ISSUE THREAD

**Issue by Y2Kot** [pedroSG94/RTSP-Server#63]
Hello, I have a problem - when I'm starting preview in portrait and rotate phone it's became 90 degree rotated in horizontal ( video sample https://disk.yandex.ru/i/UWuMd-Hxuw1gzw). How can I fix this?

Also I have an issue when starting stream in horizontal, rotating phone - totally brake aspect ratio.

**Comment by pedroSG94** [comment]
Hello,

If you are using DisplayMode I recommend you set reotation 0 always to avoid this problem.
If you are using other mode, currently rotation preview is not supported but I have plan to add it in the future.
For now the way to use the library is lock the activity rotation after start stream

**Comment by Y2Kot** [comment]
> If you are using DisplayMode I recommend you set reotation 0 always to avoid this problem.

what is DisplayMode?

**Comment by pedroSG94** [comment]
I mean RtmpDisplay or RtspDisplay classes.

**Comment by Y2Kot** [comment]
I'm using RtspServerCamera2, Seems that I can't connect RtspDisplay for it
