### ISSUE TITLE
Client/Server ports for udp are static/wrong

### ISSUE THREAD

**Issue by MalteHillmann** [pedroSG94/RTSP-Server#69]
Hi @pedroSG94 and thank you for your library!

I have problems with udp and I think thats because of this:
https://github.com/pedroSG94/RTSP-Server/blob/a88620ec6e602d7ab8e933ee41593a78d2bce839/rtspserver/src/main/java/com/pedro/rtspserver/ServerCommandManager.kt#L183

The client defines a UDP port range with its SETUP request:
`I/CommandsManager: SETUP XXX.XXX.XXX.XXX:XXXX/streamid=0 RTSP/1.0
    CSeq: 4
    User-Agent: XXX
    Transport: RTP/AVP;unicast;client_port=49670-49671`

The server recognises it correctly:
`I/ServerCommandManager: Video ports: [49670, 49671]`

But then the server sends a wrong response with some hardcoded ports:
`I/Client: RTSP/1.0 200 OK
    Server: pedroSG94 Server
    Cseq: 4
    Content-Length: 0
    Transport: RTP/AVP/UDP;unicast;destination=XXX.XXX.XXX.XXX;client_port=8000-8001;server_port=39000-35968;mode=play
    Session: 1185d20035702ca
    Cache-Control: no-cache`

I think the correct response should be something like this?
`RTP/AVP/UDP;unicast;destination=XXX.XXX.XXX.XXX;client_port=49670-49671;server_port=5002-5003;mode=play`

The client ports are those reported by the client, the server ports are defined here (named as client ports?):
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/3bbdd59707855d4ccdbaea319583716ae3f5235d/rtsp/src/main/java/com/pedro/rtsp/rtsp/commands/CommandsManager.kt#L63-L64

Maybe is the usage of these is wrong here, because the "client ports" are used as "source ports" here:
https://github.com/pedroSG94/RTSP-Server/blob/a88620ec6e602d7ab8e933ee41593a78d2bce839/rtspserver/src/main/java/com/pedro/rtspserver/ServerClient.kt#L58-L59
So maybe it should be this instead?
```
rtspSender.setSocketsInfo(commandsManager.protocol, commandsManager.videoServerPorts, 
     commandsManager.audioServerPorts) 
```

Maybe you can take a look at it? Otherwise I can do a pull request for this.

Thank you!

Kind regards
Malte

**Comment by pedroSG94** [comment]
Fixed here: https://github.com/pedroSG94/RTSP-Server/commit/70b9d56e7650edb957e20959a6f6e7a625443827

Re open issue if needed
