### ISSUE TITLE
onConnectionSuccessRtsp is never called

### ISSUE THREAD

**Issue by MalteHillmann** [pedroSG94/RTSP-Server#70]
Hi!

The function onConnectionSuccessRtsp is never called when using RTSP-Server. 

In RtspClient.kt is a call here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/3bbdd59707855d4ccdbaea319583716ae3f5235d/rtsp/src/main/java/com/pedro/rtsp/rtsp/RtspClient.kt#L284

In RtspSender.kt is only a call to onConnectionFailedRtsp but no call to onConnectionSuccessRtsp.
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/3bbdd59707855d4ccdbaea319583716ae3f5235d/rtsp/src/main/java/com/pedro/rtsp/rtsp/RtspSender.kt#L156

I think 
`connectCheckerRtsp.onConnectionSuccessRtsp()`
should be called right after this:
https://github.com/pedroSG94/RTSP-Server/blob/a88620ec6e602d7ab8e933ee41593a78d2bce839/rtspserver/src/main/java/com/pedro/rtspserver/ServerClient.kt#L75

Otherwise adaptive video bitrate can only be used with a workaround on RTSP-Server.

Thank you.

Kind regards
Malte

**Comment by pedroSG94** [comment]
Fixed here: https://github.com/pedroSG94/RTSP-Server/commit/70b9d56e7650edb957e20959a6f6e7a625443827

Re open issue if needed
