### ISSUE TITLE
Cannot stream RTSP 

### ISSUE THREAD

**Issue by annyjasmin39** [pedroSG94/RTSP-Server#75]
I tried with demo app,but in VLC it is giving error.
Code is working fine,no error or exceptions..after play method...it immediately comes to teardown method and disconnects the client.

﻿-- logger module started --
main: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
main: playlist is empty
faad error: Failed to initialize faad using extra data
avcodec error: cannot start codec (aac)
live555 error: Failed to connect with rtsp://192.168.1.33:1935
live555 error: TCP rollover failed, aborting
faad error: Failed to initialize faad using extra data
avcodec error: cannot start codec (aac)
live555 error: Failed to connect with rtsp://192.168.1.33:1935
live555 error: TCP rollover failed, aborting
faad error: Failed to initialize faad using extra data
avcodec error: cannot start codec (aac)
faad error: Failed to initialize faad using extra data
avcodec error: cannot start codec (aac)
live555 error: no data received in 10s, aborting
faad error: Failed to initialize faad using extra data
avcodec error: cannot start codec (aac)
faad error: Failed to initialize faad using extra data
avcodec error: cannot start codec (aac)
live555 error: no data received in 10s, aborting
faad error: Failed to initialize faad using extra data
avcodec error: cannot start codec (aac)
live555 error: Failed to connect with rtsp://192.168.1.33:1935
live555 error: TCP rollover failed, aborting
-- logger module stopped --

**Comment by annyjasmin39** [comment]
main error: Timestamp conversion failed (delay 1000000, buffering 0, bound 9000000)
main error: Could not convert timestamp 50810072107 for FFmpeg
main error: Timestamp conversion failed (delay 1000000, buffering 100000, bound 9000000)
main error: Could not convert timestamp 50908716129 for FFmpeg
main error: Timestamp conversion failed (delay 1000000, buffering 100000, bound 9000000)
main error: Could not convert timestamp 50908716151 for FFmpeg
main error: Timestamp conversion failed (delay 1000000, buffering 100000, bound 9000000)
main error: Could not convert timestamp 50908716162 for FFmpeg
main error: Timestamp conversion failed (delay 1000000, buffering 100000, bound 9000000)
main error: Could not convert timestamp 50908716173 for FFmpeg
main error: Timestamp conversion failed (delay 1000000, buffering 100000, bound 9000000)
main error: Could not convert timestamp 50908716195 for FFmpeg
main error: Timestamp conversion failed (delay 1000000, buffering 100000, bound 9000000)
main error: Could not convert timestamp 50908716206 for FFmpeg
main error: Timestamp conversion failed (delay 1000000, buffering 100000, bound 9000000)
main error: Could not convert timestamp 50908716217 for FFmpeg
main error: Timestamp conversion failed (delay 1000000, buffering 100000, bound 9000000)
main error: Could not convert timestamp 50908716228 for FFmpeg
main error: Timestamp conversion failed (delay 1000000, buffering 100000, bound 9000000)
main error: Could not convert timestamp 50908716239 for FFmpeg
main error: Timestamp conversion failed (delay 1000000, buffering 100000, bound 9000000)
main error: Could not convert timestamp 50908716250 for FFmpeg

**Comment by annyjasmin39** [comment]
Could you please help

**Comment by annyjasmin39** [comment]
![image](https://user-images.githubusercontent.com/76213526/181018067-d5bf8f0f-fd60-4f4e-98ce-1c6e2c8e68a5.png)

**Comment by annyjasmin39** [comment]
only blue screen getting nothing

**Comment by pedroSG94** [comment]
Hello,

Are you using app example? Do you have preview using app example?
Can you tell me VLC version and OS used?
Also, let me know device used.

**Comment by annyjasmin39** [comment]
VLC Version-3.0.17.4
OS-Windows
device-Samsung galaxy
When I checked the logcat ,i found lot of rgb2nv12 failed
it seems to be related to rgb coversion,
tried with surfaceview,openglview with camera2

Now I switched back to camera1 but there also video is stuck from the beginning-
![image](https://user-images.githubusercontent.com/76213526/181250169-cdd39dd9-b8ec-4322-81d2-97f8812b8c77.png)

**Comment by annyjasmin39** [comment]
i think this is vlc problem,in ffplay it is working fine,but i still work on rgb2nv12 issue...for camera2 api with openglview

**Comment by pedroSG94** [comment]
If the problem is only with VLC. Try to disable codec hardware acceleration:
https://www.winxdvd.com/video-transcoder/vlc-hardware-acceleration-gpu-decoding.htm

**Comment by annyjasmin39** [comment]
closing this issue,as this is much related to encoding issue,opening new issue in the library project
