### ISSUE TITLE
Non-monotonous DTS in output stream 0:0

### ISSUE THREAD

**Issue by wlxyhy** [pedroSG94/RTSP-Server#79]
When I use ffmpeg to pull stream and save video, there's timestamp errors:

[mpegts @ 0000020b535dc040] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[mpegts @ 0000020b535dc040] Non-monotonous DTS in output stream 0:0; previous: 394425663, current: -2578584943; changing to 394425664. This may result in incorrect timestamps in the output file.
[mpegts @ 0000020b535dc040] Non-monotonous DTS in output stream 0:0; previous: 394425664, current: -2578583067; changing to 394425665. This may result in incorrect timestamps in the output file.
[mpegts @ 0000020b535dc040] Non-monotonous DTS in output stream 0:0; previous: 394425665, current: -2578578540; changing to 394425666. This may result in incorrect timestamps in the output file.

The video was saved, but the images shake by time, it may stay unchange for 5 seconds then jump to 5 secondes later. Does anybody have suggestions?

**Comment by pedroSG94** [comment]
Hello,
Can you share me the command used to test it?

**Comment by wlxyhy** [comment]
ffmpeg.exe -i rtsp://192.168.0.1:2000 -c copy -f mpegts ts1001.ts

**Comment by renanaragao** [comment]
Alguma responsta?

**Comment by pedroSG94** [comment]
Hello,

If you have problem with the output you can try to stream using RTMP with:
```kotlin
 rtmpCamera.getStreamClient().forceIncrementalTs(true)
```

If this is working. I will add this method for RTSP and SRT soon

**Comment by pedroSG94** [comment]
Thank you for share the fix.

Closing as solved.
