### ISSUE TITLE
how to add more camera preview?

### ISSUE THREAD

**Issue by gobeyondmyself** [pedroSG94/RTSP-Server#80]
how to add more camera preview?

**Comment by pedroSG94** [comment]
Hello,

Currently it is not supported without change the library code. Modify OpenGlView to link it with other OpenGlView is possible but no easy to do it and affect significantly the performance. That is the reason because it is not supported by default.
Which is your requirement exactly? I don't understand the point of use 2 camera previews

**Comment by gobeyondmyself** [comment]
> Hello,
> 
> Currently it is not supported without change the library code. Modify OpenGlView to link it with other OpenGlView is possible but no easy to do it and affect significantly the performance. That is the reason because it is not supported by default. Which is your requirement exactly? I don't understand the point of use 2 camera previews

I have three cameras, three of which need to be previewed, two of which need to be streamed to the local server.Obviously, it is necessary to modify the code base.

**Comment by gobeyondmyself** [comment]
I'm not sure whether the api camera supports opening multiple cameras at the same time, but I can be sure that the api camera 2 supports it. However, I need to integrate your code to implement streaming to the local server, which is difficult.

**Comment by pedroSG94** [comment]
Hello,

Normally it is not related with camera2 or camera1 it is related with the device itself. The most of devices don't support open multiple cameras at same time so implement it in the library has no sense.
For example open front and back camera could be a case.
You can stream to any server that support rtmp or rtsp using this library:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java

**Comment by gobeyondmyself** [comment]
Yes, the device I use is rockchip, which supports simultaneous preview of multiple USB cameras. I try to use camera2 and uvcCamera to achieve this, but camera1 does not seem to support simultaneous preview. Now my question is, I want to build the rtsp server in the android client. I want to modify this library. After changing camera1 to camera2 or uvcCamera, I can use this library to implement the rtsp server. Can I do that?
