### ISSUE TITLE
Using RTSP in background doesn't work

### ISSUE THREAD

**Issue by swFan** [pedroSG94/RTSP-Server#94]
Hello ,  when i use the rtsp demo work in background, it doesn't work, I change the code as following:

 rtspServerCamera2 = RtspServerCamera2(this, true, this, 1935)
 rtspServerCamera2.setVideoCodec(VideoCodec.H264)
 

to start RTSP:
rtspServerCamera2.startStream()

but the demo will not work, who can help me?

**Comment by pedroSG94** [comment]
You have background example in RootEncoder library app module. You only need replace stream class in that example with rtspServerCamera2
Closing as inactive.
