### ISSUE TITLE
Hello, I would like to ask how to set up horizontal screen streaming

### ISSUE THREAD

**Issue by Tom-jia** [pedroSG94/RTSP-Server#95]
Is there any way to set it?

**Comment by Tom-jia** [comment]
Is there any way to set it?

**Comment by pedroSG94** [comment]
Yes, you can do it. 
You can just change the screen orientation to landscape in the project example and streaming will work in horizontal.

Also if you want change streaming orientation manually you can set the orientation to prepareVideo method with values of (0, 90, 180 or 270) but CameraHelper.getCameraOrientation(context) do it for you

**Comment by Tom-jia** [comment]
Hello, I set the resolution to 1920*1080 when pushing the stream. Use this method onTakePhoto to get the picture and save it to 1080*1920. Is there any way to solve this problem?

**Comment by pedroSG94** [comment]
Do you mean that using landscape with resolution 1920x1080 and saving image the result is 1080x1920?
Because I tested it but it is working fine in the app example. Basically i replaced switch camera button to a take photo and it is working fine.

**Comment by Tom-jia** [comment]
![image](https://github.com/pedroSG94/RTSP-Server/assets/24770231/ba75a546-3d72-4c34-adc2-0eab666b7048)
![image](https://github.com/pedroSG94/RTSP-Server/assets/24770231/a745c59a-755e-4fc2-8e5f-bd70d24f4211)
![image](https://github.com/pedroSG94/RTSP-Server/assets/24770231/87c43d99-5644-4db6-8f9b-9f31d48357a5)

**Comment by pedroSG94** [comment]
Hello,

I tested again like you but the result is working fine:
<img width="690" alt="image" src="https://github.com/pedroSG94/RTSP-Server/assets/17556876/567ffe98-eafe-494d-9ce6-9ab61b8273e9">
<img width="448" alt="image" src="https://github.com/pedroSG94/RTSP-Server/assets/17556876/c4c31a34-b63b-46f3-bdd6-9eff72ef0c24">
<img width="331" alt="image" src="https://github.com/pedroSG94/RTSP-Server/assets/17556876/08b17b1e-c182-4f26-96ab-bf27ccef4cec">

I think you are not locking screen to landscape properly. Can you share me a screenshot of the app?

**Comment by Tom-jia** [comment]
Hi, I have found a solution to this problem. Thank you very much for your support
