### ISSUE TITLE
How to pause and resume streaming?

### ISSUE THREAD

**Issue by Tom-jia** [pedroSG94/RTSP-Server#96]
Activity A jumps to Activity B and then back to Activity A. The streaming service stops and the OpenGlView screen is black. Is there any way to solve this?

**Comment by pedroSG94** [comment]
If you want continue streaming in the activity B you can use backgroudn streaming example:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/master/app/src/main/java/com/pedro/rtpstreamer/backgroundexample
