### ISSUE TITLE
rstp server creation and pushing encoded data from camera2 api 

### ISSUE THREAD

**Issue by 1goresha** [pedroSG94/RTSP-Server#97]
Is it possible to create rtsp server on one device and push h264(and AAC too) from my mediacodec there, and make it so another device can connect to this server(local network) and play this stream.
Any help would be appreciated.
Thx....

Logs:

I/Client: New client 192.168.110.221
I/CommandsManager: OPTIONS rtsp://192.168.110.147:1935 RTSP/1.0
    CSeq: 2
    User-Agent: LibVLC/3.0.18 (LIVE555 Streaming Media v2016.11.28)
I/Client: RTSP/1.0 200 OK
    Server: pedroSG94 Server
    Cseq: 2
    Public: DESCRIBE,SETUP,TEARDOWN,PLAY,PAUSE
I/CommandsManager: DESCRIBE rtsp://192.168.110.147:1935 RTSP/1.0
    CSeq: 3
    User-Agent: LibVLC/3.0.18 (LIVE555 Streaming Media v2016.11.28)
    Accept: application/sdp
I/Client: RTSP/1.0 200 OK
    Server: pedroSG94 Server
    Cseq: 3
    Content-Length: 3214
    Content-Base: 192.168.110.147:1935/
    Content-Type: application/sdp
    
    v=0
    o=- 0 0 IN IP4 192.168.110.147
    s=Unnamed
    i=N/A
    c=IN IP4 192.168.110.221
    t=0 0
    a=recvonly
    m=video 0 RTP/AVP 96
    a=rtpmap:96 H265/90000
    a=fmtp:96 packetization-mode=1; sprop-sps=Z2QACqwrQCgC3SMBBgFAACAAAAeAACE=; sprop-pps=aO48sA==; sprop-vps=QZouEP+T8N0AmBFIlomHwDiayYWB2vkiJcTlDUyTcNGaelah6j7CFy+44dK05RH60HMsukAkLm2hjoUMfEzPp98JdKjHnPzRasOm5U5bch+6H78ZHbGMliHImywMx7v9n0G1ozdxVGPIT9u4dnrG3PDSUe6YKWodLC8seVBIvMLdHiIdf1yhuaQQbDz3Z8D5+pfwiBQJ+BMt/khpH/v+S2v1vR2ahftZ1FRMiyciM40l1c8Pa2qQQ/TDL8h/lWszvE9sMHJ+TIE+G2HuUFSpZPzf3Z/ImiI1aNt5Opyo8B0F6Lpj/3mzcw34+UfJFORyYE86NCUP45dw9oHYNnOHWTgOnOZ67jWvAzbYlB7XF/zemAmJ1MSHeNSkkdldO0GvjPkh5m+aQJA7y4aXTCx9L4ow6UPVdJ3hBE1LVuDlBZuNb5J4Xxgc6AsA3F1tLQlYGKX1mho1hCI/z142nuEJiWp4bsWVAkSNVutOV3ICdguXjx3P/UEwUMHOtjJ8w7BM5OzoAHwKiMoagNBwpBrAJX5XS4tMh23UsOirN6+I9/EsnAzSJDmuRuv1tgvQUrrGzverxLtPqpPeemQeF44ZyJLN4EKI7IF/flTU+jBHYNKSC+TO8FJJkxDCGhho/Mtcb7ysDKWvPlJO2iEkwsEd6hITYmbbnURgdJSsby9GwyVzAgkS0mkxjdIirDOupfTR6JFGAUfAqyvRqmIPsdeb0fw8eBmdhe6fWQsahZPvAWQEuujGhZ2gx7NUPjgXJRsWfVg2fPNxXe2tFyhEoXvqkqcQEfxYx57kbj3X8ihA0LDD7NrSgVdI7ErSCSXAfz842E3T1fsg1XecSm0kNNFTVaG5WD/XPjMvkV1vXrkFWPtKCRDFZDdPScJR4Du/0hQB3JquAv0Hb+ZZMI5lpzCXx+ejnjT8nsldlkubnWlw8ofwAXfWzvV+s7XD29l/9NaXLte2t4gI5rYSQ85MF6uIeaR+uMOAPSj+JM2VI7UBwKoYdeNjQT4cvDdJcMJf+4Xze6TVJeugbOThQy0L4RWgPYowSLSotEpX4lbOVla8xdwVD/2XVlOE8iiF8fdLeKruIU3kE8PMOMeG5m4ho6+XugQ4dyWmOLH04G8LR5EhVkENkrVPL/oa1C38DYqIAzKhjYYP5suB5aVGUWJ3lMHX+/wFUJ5Sdib8YOFyYQMd9MX/J2V2OqtdzmE0MrsHMOKZ5UAE2OBs1/uqt+RFpz3iS/qdNbkcRqDFIwc/7+8Y9ww4hIC19LOCq56YvVxRffI1bN25V30gFNBhfD04yo9fpQJYkmKFUuQqDaKe5HVQFncePNBITxUbsGzqCIMeyOwfJz6sJBtLB9aY0NV1XKeyNsis60YQOI4855C0B7x4X2IBpmUHhVJvu30rD2KjIX7k/n2i6jhJc2OsNZ9zvkCjX0lhcG4iyLCTVoMshVhrAgXRkJLJiTsxS0ZfFO5E6Ch2p9i5O2KxLGHZg2phLgjj7FiuHgR9lj55YrGQnm966Ikxq2NTx/4kntyoPs5yaMPUST/UE6Wkjw0soTdnSUUIVshvB2QXgccHhGxZ4WSxFkID2TyqTcyROMBuPznav1z7w+/xHS9SA4MpB8axXL+S1iy6j+fLniSK8GLHGbIbxK3ev0CXuAAVwcBQW5sFtv7yd4B0mjQd0w3ugocC8L+tNwGuBNzKWfE9xyL+Vxk/pMXQ5yBoG3QXoJNQHtmhsut9bPHAdvisJ/+TiE/IjWvPm2N6JufHh23xItxferl0ZOy4YK+XaYNENjjKyfkMPp+SX31R6z/LvEWiJa6qz22ABH21L/hfUfTnIZjoyWNRRycSnXauwQDr/36L9zl80JvlEPpSj/d+u5jSkAnXHXMX9HFHVLdclNciw8JnC2myka+wwgfh+KrPdu/8ExJylhqArvHthmSOh7IX7oMfLA1zZZFX8/h5x4watnfgiL800+MY7fdKiT3+1aTWiacPmLWR3sKWyBGAHsKWjodMpwddyxWESKmsSkag0sdRpImYFkHIopoy255ipnsfq5WC5JToFI60Xu/dHLkLlM0kAL5P6YQuRP9LHqh2AyYuRzG96BZNHzLXgLjeJmSg0x0UFC8cCI8GYFyhM6eCjBaME35SmBiu6VWGZcY3EV4miNhH4EUZSJ+PBALZOUPv/88t3vu9qJm+6tmIesFC48V68O6gDE6drcYZIHK5Wu8kcLjMlx5Fwm+vIdCFbtHt6kuy51DZX3ej7P2ArtsNJcx9bgynzoMbEp4rYCO2SXDUGM362FAk61pYbAZdHPeEekNyXRV/8aQn3q83MOYbyRhDeU2ddFHBe3iGxW1WOT9D3EjRaSzwlBsPjUAu1xK3Q8arpaSM+FwQ0EWa73jRvh0ww+AGukCIHBIR9NOi3lS7g1eCnNlsJTHmC/4qpoNwsBe8hb47UJYw/uCo6zuZ8RMmBIlWwBYjAGf/KVqGNDdVSUF/eHPSZyaSiI6J75XMu8mDkbd5lJYfF4TyiEJIvUXNVuZjRHEdY6eNANajC7nw+ip3l3i1TZ77+4fdIbcCuwGAX3ZksMAbcs1et9nzvdPfqAlh9EdzKoLfowF6ZShbKTEigLcNjfvMQl0DnbcJdqkcvJM1XWEA0v59hg+WBwCjAsjL+1X+oNA2aBpteAjmftkBB4PgPeu9dYL9Rr5J2E6iHaRHeqftB8wMQA0sZuFV32nJRmAelBPQZBjSlQSUOCusUgMoOvo/K2U48FWF4BhL+HW2s5HVZy1cflvXDmSOjOBqVuruq+EVl7pG4uz0SJKF86Oc035NdtNDItv/rr3Z6xQVyOzJl1TUjq3HB90q5DvRVg0tVJ8eLzIUrDI8MyomLBICx4/RCDN1ddBmFO1Op8bJjDtdAUKBoAt/WBgaFfR1Fi7HvUlWxLynLsRQvjQI+iFKqQjUQW0ZqA==
    a=control:streamid=0
I/CommandsManager: SETUP 192.168.110.147:1935/streamid=0 RTSP/1.0
    CSeq: 4
    User-Agent: LibVLC/3.0.18 (LIVE555 Streaming Media v2016.11.28)
    Transport: RTP/AVP;unicast;client_port=63814-63815
I/ServerCommandManager: Video ports: [63814, 63815]
I/ServerCommandManager: Video ports: [63814, 63815]
I/Client: RTSP/1.0 200 OK
    Server: pedroSG94 Server
    Cseq: 4
    Content-Length: 0
    Transport: RTP/AVP/UDP;unicast;destination=192.168.110.221;client_port=63814-63815;server_port=5006-5007;mode=play
    Session: 1185d20035702ca
    Cache-Control: no-cache
I/CommandsManager: PLAY 192.168.110.147:1935/ RTSP/1.0
    CSeq: 5
    User-Agent: LibVLC/3.0.18 (LIVE555 Streaming Media v2016.11.28)
    Session: 1185d20035702ca
    Range: npt=0.000-
I/Client: RTSP/1.0 200 OK
    Server: pedroSG94 Server
    Cseq: 5
    Content-Length: 0
    RTP-Info: url=rtsp://192.168.110.147:1935/streamid=0;seq=1;rtptime=0
    Session: 1185d20035702ca
I/Client: Protocol UDP
D/RTSP_LOG: onConnectionSuccessRtsp

**Comment by 1goresha** [comment]
sorry, my bad, here:

fun sendVideoFrame(
        frame: ByteArray,
        size: Int,
        newSps: ByteBuffer,
        newPps: ByteBuffer,
        isIdr: Boolean
    ) {
        val h264Buffer = ByteBuffer.wrap(frame)

        val info = MediaCodec.BufferInfo()
        info.size = size
        info.offset = 0
        info.presentationTimeUs = System.nanoTime() / 1000 - presentTimeUs

        rtspServer?.setVideoInfo(newSps, newPps, null)   //this is whew i made a mistake,  vps should be null
        rtspServer?.sendVideo(ByteBuffer.wrap(frame), info)
    }

**Comment by pedroSG94** [comment]
Yes, if you don't use a null value the library assume that you are using h265 codec as you can see in the SETUP command


> a=rtpmap:96 H265/90000
